package.json, src/App.tsx, src/pages/ApplicationPage.tsx, src/pages/LoginPage.tsx, src/pages/MainPage.tsx, src/pages/ModelInfoPage.tsx, src/pages/MyPage.tsx, src/pages/OfferInfoPage.tsx, src/pages/SignUpPage.tsx, yarn.lock
- close #18 
<br />
```tsx
const router = createBrowserRouter([
{ path: '/', element: <MainPage /> },
{ path: '/login', element: <LoginPage /> },
{ path: '/signup', element: <SignUpPage /> },
{ path: '/modelinfo', element: <ModelInfoPage /> },
{ path: '/application', element: <ApplicationPage /> },
{ path: '/offerinfo', element: <OfferInfoPage /> },
{ path: '/mypage', element: <MyPage /> },
]);
```
- 단순하게 각 페이지명으로 라우팅 되도록 만들었는데 login 이후에는 페이지 명 뒤에 파라미터가 붙어야 하는 걸 알지만 !!! 아직 API 명세서가 안 나왔기에 페이지명까지만 지어줬습니당 ! !
=> [Setting] 라우터 기능 추가

src/styles/Theme.ts, src/styles/style.d.ts
- close #16 
<br />
```typescript
const Example = styled.div`
background: ${({ theme }) => theme.colors.ModdyGradient3};
box-shadow: ${({ theme }) => theme.effects.MainCtaShadow};
backdrop-filter: ${({ theme }) => theme.effects.MainCtaBlur};
`;
``` 
- moddyGradient가 추가되었습니다! 해당 컬러를 이용할 때에는 `background-color`가 아닌 `background`라고 적어야 적용되더라구요! 
혹시 사용하실 때 필요하실까봐 적어둡니다. 
2. 그리구 effect 두가지가 적용된 효과가 딱 하나 있는데 이걸 따로 객체로 빼버리면 theme 사용이 오히려 불편할 것 같아서
`MainCtaShadow `와  `MainCtaBlur`로 구분해두었으니 위에 코드처럼 적어서 효과 적용해주시면 됩니다! 
<br />
<br />
=> [Setting]Theme 설정 수정

src/App.tsx, src/pages/MainPage.tsx, src/views/@common/components/Button.tsx, src/views/@common/components/Header.tsx
- close #31 
<br />
- header는 scroll과 무관하게 상단에 보여야하기 때문에 `position:fixed`로 구현하였습니다. 따라서 내부 컴포넌트를 위에서부터 쌓으면 header 위치와 무관하게 맨 위부터 쌓이기 때문에 최상단 공백에 header 높이인 `5rem` 만큼 띄워주어야 합니다. 
- ⭐️navigate 혹은 이탈 모달을 띄우기 위한 onClick 함수를 넣어야하실텐데요, 
- **뒤로가기** 버튼에 넣을 onClick함수는 `backFn`에 
- **닫기** 버튼에 넣을 onClick함수는 `closeFn`에 담아주시면 됩니다. 
- 두 함수의 type은 `()=>void` 로 맞춰주셔야 합니다. 
- ⭐️사용법
- isBackBtnExist : 뒤로가기 버튼 필요 여부 (boolean) 
- isCloseBtnExist : 닫기 버튼 필요 여부 (boolean) 
- title : 헤더에 들어가는 텍스트. 없을 시 빈 문자열 
- backFn : 뒤로가기 버튼 onClick
- closeFn : 닫기 버튼 onClick
```jsx
<Header isBackBtnExist={true} isCloseBtnExist={false} title="헤더 제목" />
<Header isBackBtnExist title="자유롭게" />
<Header
isBackBtnExist={true}
isCloseBtnExist={true}
title="제목 내용"
backFn={() => {
navigate(-1);
}}
/>
```
- 버튼은 현재 양옆 1.5rem의 공백, 아래엔 …
=> [Common] 공통 컴포넌트 - Header, CTA 구현

src/pages/MainPage.tsx, src/styles/Theme.ts, src/styles/style.d.ts, src/views/@common/components/Button.tsx, src/views/@common/components/Input.tsx, src/views/@common/components/ProgressBar.tsx, src/views/@common/components/TextArea200.tsx, src/views/@common/components/ToastMessage.tsx
close #74 
<br />
▶️**interface**
```ts
interface ButtonProps {
text: string;
isFixed?: boolean;
onClickFn: () => void;
disabled?: boolean;
icon?: ReactNode;
shadow?: boolean;
}
```
▶️**사용법**
shadow 필요한 경우 shadow 넣기 
```tsx
<Button text="다음" onClickFn={() => console.log('test')} isFixed shadow />
```
<br />
=> [Common] ProgressBar, Button, Toast 수정사항 반영

src/styles/GlobalStyle.ts, src/views/MainPage/components/TopSheet.tsx, src/views/MainPage/hooks/useStatusBarColor.tsx
close #123
<br />
`useEffect` 에서 return 문은 unmount시 발생할 행동이다
따라서 다음과 같이 작성하여  해결하였다
```javascript
return () => {
window.removeEventListener('scroll', handleScroll);
document.body.style.backgroundColor = '#ffffff';
};
```
=> [MainPage] 다른 페이지로 이동했을 때 배경색 이슈 해결

index.html, package.json, src/App.tsx, src/pages/MainPage.tsx, src/recoil/atoms/signUpState.ts, src/views/@common/components/Input.tsx, src/views/@common/hooks/api.ts, src/views/@common/utils/constants.ts, src/views/@common/utils/userType.ts, src/views/MainPage/components/ReceivedOffer.tsx, src/views/MainPage/components/TopSheet.tsx, src/views/SignUpPage/components/EnterProfile.tsx, src/views/SignUpPage/components/PersonalInfo.tsx, src/views/SignUpPage/components/RegionItem.tsx, src/views/SignUpPage/components/SelectPreferRegion.tsx, src/views/SignUpPage/components/SelectUserType.tsx, src/views/SignUpPage/components/VerifyPhoneNumber.tsx, src/views/SignUpPage/constants/userType.ts, yarn.lock
close #126 
<br />
컴포넌트 이동 시에 너무 많은 데이터를 가지고 다녀야해서 `recoil`을 도입하게 되었습니다!
유저타입(디자이너/모델) 은 `recoil-persist`로 local storage에 저장하여 main이동 시 판별하여 해당 컴포넌트를 뿌려주도록 하였습니다.
```javascript
const { persistAtom } = recoilPersist();
export const userTypeState = atom({
key: 'userType',
default: null,
effects_UNSTABLE: [persistAtom],
});
const MainPage = () => {
const userType = useRecoilValue(userTypeState);
const applyType = APPLY_TYPE.NOT_YET;
return (
<MainPageLayout>
...
{!userType ? <Contents /> : <ReceivedOffer applyType={applyType} />}
</MainPageLayout>
);
};
```
아직 recoil에 익숙하지 않아서 구현 방식에 대한 조언도 있으면 부탁드려용
```javascript
export const nameState = atom<inputDataType>({
key: 'name',
default: {
data: '',
verifyStatus: false,
},
});
export const birthYearState = atom<inputDataType>({
key: 'birthYear', …
```
=> [SignUpPage] 유저 입력 데이터 관리

src/App.tsx, src/main.tsx, src/views/@common/hooks/api.ts, src/views/LoginPage/components/LoginButton.tsx, src/views/LoginPage/components/LoginCallback.tsx, src/views/LoginPage/constants/kakaoLink.ts, src/views/LoginPage/hooks/type.ts, src/views/LoginPage/hooks/usePostLogin.ts
close #122 
<br />
**1️⃣ 서버에게 받은 Rest api key와 Redirect URI로 카카오 로그인 링크를 생성한다.** 
```ts
export const KAKAO_LINK = `https://kauth.kakao.com/oauth/authorize?client_id=${KAKAO_REST_API_KEY}&redirect_uri=${KAKAO_REDIRECT_URI}&response_type=code`;
```
**2️⃣ 로그인 버튼 onClick 에 카카오 로그인 링크로 이동하는 handler를 연결해준다.** 
```ts
const handleLogin = () => {
window.location.href = KAKAO_LINK;
};
```
3️⃣ 로그인을 진행하면 **링크가 이동하면서 서버가 줬던 redirect uri로 이동**하는데, 주소 뒤 queryString으로 code={인가코드}가 붙는다. 
**4️⃣ redirect uri로 이동했을 때 실행할 컴포넌트를 생성한다**
```ts
{ path: '/login/oauth2/code/kakao', element: <LoginCallback /> }
```
```tsx
import usePostLogin from '../hooks/usePostLogin';
const LoginCallback = () => {
usePostLogin(); // 인가코드를 서버에게 보내주는 post 통신 hook 
return <div></div>;
};
export default LoginCallback;
```
**5️⃣ 인가코드를 …
=> [LoginPage] 리드의 지조를 지키기 위해 만든 카카오 로그인 PR 

src/main.tsx, src/pages/AgreementPage.tsx, src/recoil/atoms/signUpState.ts, src/views/AgreementPage/components/AgreementList.tsx, src/views/SignUpPage/components/PersonalInfo.tsx, src/views/SignUpPage/components/PreferRegion.tsx, src/views/SignUpPage/components/RegionItem.tsx, src/views/SignUpPage/hooks/type.ts, src/views/SignUpPage/hooks/useGetRegion.ts, src/views/SignUpPage/hooks/useModelSignUp.ts
close #139 
<br />
커스텀 훅 로직 부분에서 조언 받습니다
<br />
선호 지역 선택 화면에서 뒤로 갔다 다시 올 때 데이터를 안불러오는 이슈가 있어서
계속 시도하다가,, 선호지역도 전역상태로 관리해주었습니다
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/46593078/03a4d36e-4c34-4d97-b967-c31295e7d4fa
=> [SignUpPage] 모델 회원가입 API 연동

src/recoil/atoms/signUpState.ts, src/views/SignUpPage/components/UserType.tsx, src/views/SignUpPage/hooks/useModelSignUp.ts
close #174 
<br />
디자이너/모델 선택 후 회원가입 중 메인으로 넘어가게 되면 해당 메인으로 넘어가져서 임시저장용 / 스토리지 저장용 atom을 분리하여 관리하여 해결하였습니다
=> [SignUpPage] 가입 프로세스 끝나고 유저 타입 스토리지에 저장

src/pages/ModelInfoPage.tsx, src/pages/OfferDetailSection.tsx, src/views/ModelInfoPage/components/DetailBox.tsx, src/views/ModelInfoPage/hooks/types.ts, src/views/ModelInfoPage/hooks/useGetApplication.ts
close #195 
<br />
```tsx
// 임시용 applicationId
const APPLICATION_ID = 1;
const { data, isLoading, isError } = useGetApplication(APPLICATION_ID);
```
- api endpoint에 applicationId가 필요한데, 메인뷰랑 연결하기 전 단계라서 임시 index 1로 넣어놨습니다 
```tsx
return (
!isError &&
!isLoading &&
data && (
<>
<Header isBackBtnExist={true} title="모델 지원 정보" />
<S.ModelInfoLayout>
<S.ImageBox src={data.applicationInfo.modelImgUrl} alt="모델 이미지"></S.ImageBox>
<OfferDetailSection handleCopyClipBoard={handleCopyClipBoard} data={data} />
</S.ModelInfoLayout>
<Button text="제안하기" isFixed={false} onClickFn={handleOnClickOffer} />
{isToastOpen && <ToastMessage text="아이디 복사가 완료되었습니다." setter={setToastOpen} />}
</>
)
```
- isError와 isLoading이 false고, data 값 있을 때 렌더링 
- OfferDetailSection에 data로 { applicationInfo: ~ , modelInfo: ~ } …
=> [ModelInfoPage] useGetApplication API 연결

src/views/OfferInfoPage/components/ButtonBox.tsx, src/views/OfferInfoPage/components/CheckOfferPage.tsx, src/views/OfferInfoPage/components/DirectionModal.tsx, src/views/OfferInfoPage/components/ImgModal.tsx, src/views/OfferInfoPage/components/ProfileWrapperBox.tsx, src/views/OfferInfoPage/hooks/type.ts, src/views/OfferInfoPage/hooks/useGetAgree.ts
close #194 
<br />
offerId는 OfferInfoPage의 GET 통신에서 받을 수 있습니다 
해당 데이터를 useGetAgree에 보내주기까지의 경로는 아래와 같습니다. 
`OfferInfoPage -> DirectionModal -> CheckOfferPage -> useGetAgree`
- 따라서 `OfferInfoPage -> DirectionModal` 은 props drilling으로 
- `DirectionModal -> CheckOfferPage`는 navigation시 state로 
- `CheckOfferPage -> useGetAgree`는 함수 인자로 전달해줍니다. 
- CheckOfferPage에서 useGetAgree 호출 및 데이터 페칭 
```json
// 형태 
"data": {
"applicationImgUrl" : "http://지원내역 캡쳐한거 클라가 넘겨준거 저장해둔거 보내쥼",
"kakaoUrl" : "http://카카오톡 url",
"designerInfo": {
"imgUrl" : "http://디자이너이미지겠죠?",
"shopName" : "모디 헤어1",								
"name" : "백모디1",
"introduction" : "디자이너 자기소개 입니다.",
}
}
```
- ButtonBox : data.kakaoUrl 전달 
- ImgModal : data.applicationImgUrl 전달
- ProfileWrapperBox : data.designerInfo 전달 
<br />
=> [OfferInfoPage] useGetAgree API 구현 

src/views/SignUpPage/components/PhoneNumber.tsx, src/views/SignUpPage/constants/message.ts, src/views/SignUpPage/hooks/type.ts, src/views/SignUpPage/hooks/usePostPhoneNumber.ts, src/views/SignUpPage/hooks/usePostVerifyPhoneNumber.ts
close #213
<br />
전화번호 11자 안됐을 때도 버튼이 눌리길래 휴대폰 번호가 검증 됐을 때만 요청 가능하도록 수정했습니다
성공했을 떄 다시 요청할 수 없도록 인증 성공 시 input, button 을 disabled 처리 했습니다
<br />
`postVerifyPhoneNumber`를 수행하고나서 그 여부에 따라 `status`를 바꿔줘야 했습니다
`postVerifyPhoneNumber` 함수가 `비동기`이므로, 그 함수의 실행 결과를 기반으로 상태를 업데이트하려면
1) **해당 함수 내에서 상태 업데이트** 로직을 처리하거나,
2) 함수가 프로미스를 반환하도록 하고 **await를 사용하여 결과를 기다린 후 상태를 업데이트**해야 했습니다
커스텀 훅 파일에서 전역상태를 또 한번 불러오는 것은 낭비이기 떄문에 `2번` 해결방법을 사용하였습니다
```javascript
const handleConfirmVerify = async () => {
if (seconds > 0) {
if (verifyCode.status === STATUS.AVAILABLE) {
const success = await postVerifyPhoneNumber();
if (success) { // 성공시 상태값 업데이트
setPhoneNumber({
data: phoneNumber.data,
status: STATUS.DONE,
});
setVerifyCode({
data: verifyCode.data,
status: STATUS.VERIFIED,
});
} else {
setToastOpen(true); // 잘못된 …
```
=> [SignUpPage] 전화번호 인증 API 연결

src/views/LoginPage/hooks/type.ts, src/views/LoginPage/hooks/usePostLogin.ts
close #217 
<br />
res.data.data. 이렇게 더럽게 불러오고 있는거
추후 로그인 API 다시 확정될 경우 타입 정의 다시 해서 정리할 예정입니다 ~! 
<br />
=> [LoginPage] 변경된 로그인 로직 반영 및 useType set

src/views/LoginPage/hooks/usePostLogin.ts
- close #256 
<br />
localStorage에서 불러오는 userType이 로그인시 들어오는 response를 그대로 박아줬는데, 
수빈이 쪽에서 endpoint에 바로 사용하기 때문에 분기처리해서 다른 값으로 넣어주었습니다 ! 
```ts
.then((res: loginResProps) => {
const { role, accessToken } = res.data.data;
setToken(accessToken);
setUserType(role === 'MODEL' ? 'model' : 'designer');
navigate('/');
})
```
=> [bugfix] response 값에 따라 userType 분기 저장

src/views/@common/utils/removeToken.ts, src/views/LoginPage/hooks/usePostLogin.ts, src/views/MyPage/hooks/useDeleteUser.ts, src/views/MyPage/hooks/usePostLogout.ts
- close #256 
<br />
localStorage에 있는 type을 삭제해주어도 401 에러가 나는 문제가 있었습니다. 
localStorage가 recoilState에 동적으로 바로바로 반영되지 않는 문제인 것으로 추측되어 
별도로 recoilState를 USER_TYPE.GUEST로 초기화해주어서 해결했습니다 
**-> useResetRecoilState 활용하여 userType 초기화 방식으로 변경** 
```ts
const resetType = useResetRecoilState(userTypeState);
await api.post('/auth/logout', null);
removeToken();
resetType();
navigate('/');
```
<br />
=> [bugfix] 회원탈퇴, 로그아웃 시 recoil state 초기화 

index.html, src/views/MainPage/components/Card.tsx
- close #300
메인뷰 지원/제안서 카드 이미지가 중앙에 안오고 위에부터 나옴
<br />
background img 로 넣어서 center/cover 로 중앙에 맞춰줬습니다
```css
background: center/cover ${({ $img }) => `url(${$img})`} no-repeat;
```
<br />
=> [QA] 메인뷰 지원서/제안서 사진 위치 조정

src/pages/OfferDetailSection.tsx
- close #i304
인스타그램 아이디가 선택사항인데 빈 값일때 없음 입력 및 아이디 복사 방지 기능 추가
<br />
```typescript
{modelInfo.instagramId ? (
<>
<OfferDetail content={modelInfo.instagramId}>인스타그램</OfferDetail>
<CopyButton onClickFn={() => handleCopyClipBoard(modelInfo.instagramId)} />
</>
) : (
<OfferDetail content="없음">인스타그램</OfferDetail>
)}
``` 
<br />
=> [QA]인스타그램 복사 아이디 조건부 렌더링

src/recoil/atoms/signUpState.ts, src/views/@common/hooks/api.ts, src/views/@common/utils/removeToken.ts
- close #299 
A기기를 쓰던 유저가 B기기로 옮겨서 서비스를 이용하다가 탈퇴를 하면, 
A기기는 계속 토큰이 저장되어있기 때문에 에러가 발생하게 될 수 있다. 
이러한 경우를 대비하고자 로그인토큰을 localStorage가 아니라 sessionStorage로 저장하고자 한다. 
<br />
userTypeState와 카카오 토큰을 sessionStorage로 관리한다. 
⭐️ 브라우저를 킬때마다 로그인이 풀려있으면 사용성이 떨어지지 않을까 고민했으나, 카카오 자체 캐시 덕분에 카카오로그인의 과정이 생략되어 사용성에 문제가 없다는 결론을 내렸다! 
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/5c284760-7f8b-4169-914f-fa12e6d1234a
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/457670a7-e4d8-4e34-913a-ac2e5e0a9b0e
=> [QA] token과 userType local->SessionStorage

src/views/MainPage/hooks/useGetMain.tsx
- close #303 
메인페이지에서 오류가 났을 경우 에러페이지로 이동해서 아무것도 할 수 없는 굴레에 빠짐..
<br />
사용자가 휴대폰으로 토큰을 지워줄 수 없기 때문에 에러핸들링에 토큰 삭제 후 강제 새로고침 처리
```javascript
catch (err) {
removeToken();
location.reload();
}
```
=> [QA] 메인페이지 통신 오류시 에러 헨들링 로직 수정

src/views/OfferInfoPage/components/DirectionModal.tsx, src/views/OfferInfoPage/components/ImgModal.tsx
- close #323
header의 z-index 수정하면서 img modal 위로 올라가게 되었어요
<br />
z-index: 5먹였습니다~~~
<br />
=> fix: z-index 수정

src/views/ApplicationPage/components/DefaultInfo.tsx, src/views/ApplicationPage/components/StyleButton.tsx
- close #307 
체크 박스를 선택하고 다음단계 갔다가 돌아오면 체크 여부가 반영되지 않는 문제가 발생
<br />
처음엔 각 styleButton 컴포넌트에서 useEffect를 통해 체크 활성화/비활성 여부를 렌더링 해주도록 설정
공식 문서에 의하면
> 기본적으로 동작은 모든 렌더링이 완료된 후에 수행됩니다만, 어떤 값이 변경되었을 때만 실행되게 할 수도 있습니다.
다음과 같이 나와있다.
따라서, 이미 렌더링이 완료된 상태에서 함수가 실행되기 때문에 이미 지정해준 활성화 여부의 초기값(false)에서 변경이 되지 않는 것이었다 ! ! !
<결론>
상위 컴포넌트로 체크박스 활성화 여부를 state로 빼주었다.
```tsx
const activateCheckbox = (type: string): boolean => {
return preference.some((element) => element === type);
};
```
`Array.prototype.some()` 메서드 이용
> ❓`some()` 메서드는 배열 안의 어떤 요소라도 주어진 판별 함수를 적어도 하나라도 통과하는지 테스트한다면 true를 반환하고 그렇지 않으면 false를 반환합니다. (배열을 변경하지는 않는다)
<br />
- 기본 스타일 선택으로 되돌아가기
- 최종 결과 화면
=> [QA] 희망스타일 state 미반영 사항 수정

src/views/MainPage/components/UserContents.tsx
- close #321
기획이 워딩 수정 요청하여 변경하였습니다
<br />
```tsx
<S.HelperTextSpan>
{'status' in data && data.status === APPLY_STATUS.NOTHING ? (
'지금 바로 헤어모델에 지원해 보세요 :)'
) : '조금만 기다리면 <br /> 디자이너의 모델 제안을 문자로 보내드릴게요'}
</S.HelperTextSpan>
```
이렇게 했는데 br태그가 그대로 출력됐습니다..
> React에서 JSX는 HTML과 유사하지만, 문자열 내에서 HTML 태그를 직접 사용하는 것은 기본적으로 지원되지 않습니다. 이는 보안상의 이유로, React는 문자열 내의 HTML을 그대로 렌더링하지 않고 이스케이프 처리합니다. 따라서 `<br />` 태그가 문자열로 인식되어 개행이 적용되지 않는 것입니다.
해결 방법 
1. **`dangerouslySetInnerHTML` 사용**
```jsx
<S.HelperTextSpan dangerouslySetInnerHTML={{ __html: 'status' in data && data.status === APPLY_STATUS.NOTHING
? '지금 바로 헤어모델에 지원해 보세요 :)'
: `조금만 기다리면 <br />디자이너의 모델 제안을 문자로 보내드릴게요` }}>
</S.HelperTextSpan>
```
1. **`JSX 요소` 사용**
```jsx
<S.HelperTextSpan>
{'status' in data && data.status === APPLY_STATUS.NOTHING
? '지금 …
```
=> [QA] 메인 뷰 아래 박스 라이팅 수정

src/views/OfferInfoPage/components/ImgModal.tsx
- close #325 
이미지가 안들어오고, 버튼의 레이아웃이 안맞는 이슈입니다. 
<br />
이미지 저장하기 버튼을 기존엔 button 태그를 사용하다가, 
이미지 다운로드 방식이 다운로드 url을 접속하는 방식으로 바뀌면서 a태그로 변경해주었습니다. 
button 태그는 display: block이고, a태그는 display: inline이라서 해당 문제가 발생한 것이어서 
display를 block으로 지정해주어 해결했습니다 . 
<br />
=> [QA] 이미지 저장하기 버튼 스타일 변경

src/pages/AgreementPage.tsx, src/views/MainPage/components/TopSheet.tsx, src/views/SignUpPage/components/UserType.tsx
- close #335
렌더링 시 짧았다가 길어져버려~
사용자경험이 좋지 못해요
<br />
height 기본 값 설정
<br />
이거 하다가 아까 이용약관 페이지에서 뒤로 갔을 때 홈화면으로 처리해서 login페이지로 가도록 수정해줬어요 (이슈안파서 미안합니다)
=> [QA] 렌더링이 느린 요소에 height 지정

src/views/OfferInfoPage/components/ImgModal.tsx, src/views/OfferInfoPage/hooks/type.ts, src/views/OfferInfoPage/hooks/usePostDownloadUrlOffer.ts
- close #351 
지원서 이미지를 다운로드 받으면 비어있는 html이 다운로드됨 
<br />
나는 Response.downloadUrl로 접근하고 있었고,
서버는 Reponse.offerImageUrl로 주고 있어서 이미지를 못받은 것이었음. 
다시 제대로 접근해서 이미지 다운로드에 성공했다. 
<br />
=> [QA] response key 변경하여 해결

src/views/@common/components/Input.tsx, src/views/@common/utils/regex.ts
- close #359
<br />
- 정규식에 따른 검증 기능 추가
- 최대 길이 제한 기능 추가
- 숫자만 입력 가능 기능 추가
<br />
승희님의 의견을 반영하여 regex는 필수 속성이 아닌 선택 속성으로 수정하였고
기본값은 NOT_EMPTY (빈 값이 아닐 때) 입니다. 다른 검증식이 필요하다면 props로 넘겨주세요
클린하게 하기 위해서 regex는 상수화 하면 좋겠죠?
이 공통 컴포넌트를 리팩한 이유이죠 !! 같은 디자인을 사용하기 때문에 이 Input으로 바꿔주시면 됩니다
`maxLength` prop을 통해 동일하게 사용가능합니다!
추가로, 숫자 입력 옵션 적용시 'tel' 타입의 키패드를 띄워 UX를 개선하였습니다
=> [Common] Input 컴포넌트 변경

src/pages/MainPage.tsx, src/views/@common/utils/UsePreventGoBack.ts, src/views/MainPage/components/Card.tsx, src/views/MainPage/components/TopSheet.tsx, src/views/MainPage/components/UserContents.tsx, src/views/MainPage/constants/constant.ts, src/views/MainPage/hooks/useGetMain.ts
- close #362 
<br />
- 뒤로 가기 막기 로직 개선 
- 가독성을 위해 메인페이지 분기를 컴포넌트 매핑으로 처리
- 재사용성을 위한 카드 컴포넌트에 합성 컴포넌트 패턴 적용
- 탑시트안의 컴포넌트 추상화
- ReceivedOffer & ApplicationOffer 를 GuestContents와의 네이밍 통일을 위해 변경 (ModelContents, DesignerContents)
- 메인 서버 통신 로직 데이터 분리를 통한 분기 로직 개선
<br />
**변경 전**
```jsx
const MainContents = () => {
switch (userType) {
case USER_TYPE.GUEST:
return <GuestContents />;
case USER_TYPE.DESIGNER:
return designerData && <DesignerContents data={designerData} setPage={setPage} />;
case USER_TYPE.MODEL:
return modelData && <ModelContents data={modelData} setPage={setPage} />;
default:
return null;
}
};
return (
<MainPageLayout>
<TopSheet
userType={userType}
applyType={userType === USER_TYPE.MODEL && modelData ? modelData.status : ''}
name={data ? data.name : ''}
/>
<MainContents /> …
```
=> [MainPage] 분기 처리 로직 개선

src/views/@common/hooks/useSetInterceptors.ts
- close #388 
<br />
<br />
새로고침하면 메인페이지에서 자동으로 로그아웃 되고, 다른 페이지에서는 AccessToken이 없다는 에러가 발생했습니다
interceptors가 제 역할을 잘 못해주고 있다는 뜻인데요 
열심히 원인을 파악한 결과, 
최상위 라우트 컴포넌트인 Settings 내부의 useEffect보다, 자식 라우트인 다른 컴포넌트들의 내부에 있는 useEffect가 먼저 실행되어 
새로고침한 직후 axios interceptors를 세팅해주는 코드보다 각 페이지 로드 시 첫 get 통신이 먼저 실행되어서 토큰이 담기지 않아 생긴 문제였습니다. 
자식 컴포넌트의 useEffect가 부모 컴포넌트의 useEffect보다 먼저 실행되는 것은 리액트의 생명주기와 관련이 있는데요, 
useEffect는 컴포넌트가 마운트 된 후, 즉 DOM이 그려진 후에 실행되는 친구입니다. 
그럼 부모 컴포넌트의 useEffect는 부모 컴포넌트의 DOM이 그려진 후에 실행이 될테고, 
부모 컴포넌트의 DOM이 그려지는 과정에서 자식 컴포넌트들의 DOM이 그려지고 자식 컴포넌트들의 useEffect가 모두 실행될테니, 
그 이후에 부모 컴포넌트의 useEffect가 실행되는 방식인데요 
즉 현재상황에서 필요한 것은 **DOM이 그려지기 전에 코드가 실행되어야 한다** 였습니다. 
열심히 구글링을 해보니 해당 역할을 해주는 useLayoutEffect라는 훅이 있더라고요 
그래서 이 친구를 바로 적용해서 깔끔히 해결해주었습니다. …
=> [hotfix] 새로고침할 경우 accessToken이 안담기는 문제 해결 

src/recoil/atoms/applicationState.ts, src/views/ApplicationPage/components/CaptureSection.tsx, src/views/ApplicationPage/hooks/useCaptureApplication.ts, src/views/ApplicationPage/hooks/usePostApplication.ts, src/views/ApplicationPage/utils/captureImage.ts
이번엔 리스본 💚❤
이쁘죠 ??? 이번 여행 최애 도시가 되었습니다
PR을 좀 더 빨리 날리고 싶었는데 관광하느라 지금 날리는 점,, 미안하구 이해 바랍니다 모비들아,,ㅎㅎ
<hr />
- close #345
<br />
- GET 무한 렌더링 오류 수정
- 훅 함수 유틸 함수로 분리
<br />
합숙 때부터 골머리였던 GET 렌더링 이슈를 드디어 해결했습니다.
처음에 @lydiacho 의 도움을 받아서 코드를 짜느라 제 코드를 만드는 데에 시간이 걸렸던 거 같은데 **승희님이 해결하신 렌더링 이슈 방법**도 궁금합니다 ! ! ! 코멘트로 남겨주시거나 개인적으로 연락해주시면 감사하겠습니다 ㅎㅎ
캡처하는 영역을 상태에 저장하는 과정을 상위 컴포넌트에서 해결해주었습니다.
```tsx
//수정 전, 하위 컴포넌트
useEffect(() => {
ref && setImage(ref);
}, [ref]);
//수정 후, 상위 컴포넌트
useEffect(() => {
captureImage(ref.current).then((file) => {
file && setImgData(file);
});
}, [ref.current]);
```
`useRef`를 선언하면서부터 이미 객체를 만들어낸 상태이기 때문에 `ref`라는 객체는 항상 존재할 수 밖에 없는데 하위 컴포넌트에서 `ref`의 존재유무에 의해 리렌더링이 발생하도록 만들어놔서 무한 리렌더링이 발생하고 있다는 생각이 들었습니다.
그래서 의존성 배열 및 처리 로직을 위와 같이 조금씩 수정해주었습니다.
위의 코드에 의하면
`ref` 객체가 처음 잡혔을 때 1번, 모든 …
=> [ApplicationPage] 지원 결과서 이미지 캡처 렌더링 문제 수정

src/views/@common/components/Header.tsx
- close #406 
<br />
- 워딩 변경
<br />
반영 중에 이 모달이 회원가입 중단 시에만 사용하는 것이 아니라 다른 곳에서도 사용되고 있더라고요,
그런데 지금 해당 모달이 공통 컴포넌트 Header에 들어 있습니다
**그런데 X를 누르더라도 다른 모달이 뜨는 경우가 있을 수 있을 것 같습니다**
(현재는 모든 header의 x 버튼을 눌렀을 때 작성을 중단할까요? 모달이긴 하지만요)
그래서 **이 모달은 header에 closeFn을 이용해서 사용하는 컴포넌트에서 불러야하는게 맞지 않을까?** 라는 생각이 들었습니다
**다른 분들도 의견 주시면 감사하겠습니다 🚀**
만약 해당 방식으로 바꾸는 것에 다들 찬성한다면 리팩토링 기간에 고쳐보면 좋을 것 같습니다! (저만 바꾸면 되는게 아니라..)
<br />
=> [SignUpPage] 회원가입 중단 시 모달 워딩 변경

src/App.tsx, src/pages/ApplicationConfirmPage.tsx, src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/ApplicationPage/constants/message.ts, src/views/ApplicationPage/hooks/usePostApplication.ts
- close #410
<br />
- ResponseBody로 전달오는 지원서 만료 예정 정보 추가
<br />
`usePostApplication`으로 `ApplicationPage`에서 서버와 통신하고 있었는데 `ApplicationConfirmPage`에서 서버의 ResponseBody로 전달오는 정보를 불러와야하는 상황이 발생했습니다.
```tsx
//ApplicationPage에서 서버 통신시 실행 구문
navigate(`/application/confirm`, {
state: {
expireDate: data.data.expireDate,
},
});
//ApplicationConfirmPage
const {
state: { expireDate },
} = useLocation();
```
다음과 같이 `useNavigate`훅의 `state`에 정보값을 저장해서 만료 날짜를 불러올 수 있게 만들어주었습니다 !
<br />
=> [ApplicationPage] 지원서 만료 예정 정보 추가

src/pages/ApplicationPage.tsx, src/views/ApplicationPage/components/Profile.tsx, src/views/ApplicationPage/constants/message.ts
- close #414
<br />
- 기존 컴포넌트를 공통 컴포넌트로 교체
<br />
민서가 만들어준 공통 컴포넌트를 쇽샥해서 제 페이지에 적용시켜놓았습니다.
💭별다른 PR point는 없지만 이렇게 해주면서 민서와 저의 `프로필 업로드` 관련 컴포넌트가 `input` 박스 하나의 유무를 제외하고는 동일해졌습니다.
그래서 차후 다시 있을 리팩 기간에 분기 처리하는 방식을 사용해서 하나의 컴포넌트로 합칠까 합니다 !
추가로 어제 민서와 요 프로필 업로드 컴포넌트에 대해 이야기하면서 서버와 통신 완료~ 했다는 안내를 띄워주는 `confirm 페이지`를 수빈이가 저번에 미미나 열어준 합성 컴포넌트 방식으로 구현하면 어떨까 해서 의견을 제시해 봤는데요 ! ! ! 구현하게 된다면 PR 올리겠습니당
(똑같이 디자이너일 때와 모델일 때로 분기 처리를 하지 않을까 싶습니다 ㅎㅎ)
<br />
=> [ApplicationPage] 이미지 용량 초과시 업로드 제한 및 모달 출현 공통 컴포넌트 적용

src/views/ApplicationPage/components/ServiceHistory.tsx, src/views/ApplicationPage/components/ServiceHistoryListItem.tsx
- close #363
<br />
- 단일 드롭다운 활성화
- 드롭다운 외부 영역 클릭시 드롭다운 닫기
- 상태 관리 리팩토링
<br />
이번 리팩토링의 목표는 **‘한 번에 하나의 드롭다운만 활성화되게 만들기’**입니다.
.![image](https://github.com/TEAM-MODDY/moddy-web/assets/101045330/10388ecb-fbb0-4642-96e7-8031e5c68d62)
얘처럼 와랄라 말고
얘처럼 무조건 하나만 !
1. listItem 컴포넌트 내에서 state 두개를 하나로 전환 - period와 service 를 구분해주는 state / 함수도 하나로 통일
현재 `ServiceHistoryItem` 내부에서 왼쪽 드롭다운과 오른쪽 드롭다운을 구분해주기 위해 각각의 선택 여부를 `isServiceClicked`와 `isPeriodClicked`로 다루어주고 있는데 `clickedDropdown`이라는 하나의 상태로 통합해주었습니다 !
```tsx
const [clickedDropdown, setClickedDropdown] = useState<string | null>(null);
```
왼쪽 드롭다운을 클릭하면 `clickedDropdown`에 `service`라는 `string` 값이 저장되고 오른쪽 드롭다운을 클릭하면 `serviceTerm`이라는 `string` 값이 저장됩니다.
드롭다운 선택지를 클릭하면 전역 상태에 저장되게 하는 함수도 하나로 통합했습니다.
```tsx
const handleDropdownClick = (
event: …
```
=> [ApplicationPage] 시술 내역 드롭다운 박스 단일 활성화 기능 추가

index.html, src/styles/GlobalStyle.ts, src/views/MainPage/components/GuestContents.tsx, src/views/MainPage/hooks/useStatusBarColor.ts
- close #423
<br />
로그인 이동 시 animation이 작동하여 상태바 색상이 어색하게 바뀌는 이슈
처음에 `<meta name="theme-color" />`를 이용하여 구현하려하였으나 스크롤 시 색상전환이 부드럽지 못하여 css animation을 적용하기 위해서 body에 animation을 주고 스크롤 위치에 따라 색을 정해주는 방법으로 구현을 하였습니다,
하지만 이렇게 할 경우 다른 뷰로 이동시에도 animation이 작동하여 어색한 느낌을 주고 있었습니다.
https://github.com/TEAM-MODDY/moddy-web/assets/46593078/61b7f4a4-71bd-4a01-963e-907b2e3a69b4
<br />
theme-color에 알고리즘을 통해 animation처럼 구현할 방법을 찾아보았습니다.
키프레임 애니메이션의 원리는 보간(Interpolation)입니다
이 보간법을 사용하면 시작점과 끝점 사이의 값을 부드럽게 전환하는 것이 가능해 질 수 있습니다
```ts
const interpolateColor = (startColor: string, endColor: string, progress: number): string => {
const start = hexToRgb(startColor);
const end = hexToRgb(endColor);
const r = Math.round(start.r + (end.r - start.r) * progress);
const g = Math.round(start.g + (end.g - start.g) * …
```
=> [MainPage] 로그인 이동 시 animation이 작동하여 상태바 색상이 어색하게 바뀌는 이슈 해결

src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/ApplicationPage/components/DefaultInfo.tsx, src/views/ApplicationPage/components/DetailedStyle.tsx, src/views/ApplicationPage/components/Profile.tsx, src/views/ApplicationPage/components/ServiceHistory.tsx, src/views/ApplicationPage/hooks/useResetApplicationRecoil.ts
- close #344 
<br />
- 리코일 초기화 유틸 함수 생성
- 초기화 시점 변경
<br />
💬기존 코드
기존에는 모델 지원을 완료 페이지에서 확인 버튼을 누르면 초기화를 시켰습니다.
이때, 1. 모델 지원 과정 중도 이탈시 2. 확인 안 누르고 뒤로가기 버튼 누를시 ..
등등의 상황에서 전역 상태가 안 지워지고 그대로 남아있다는 문제가 있어서 변경해주었습니다.
💬변경 코드
1. 리코일 초기화 함수 생성
2. x(닫기) 버튼 누를 시에 함수 호출 되도록 해줬습니다
> 훅이 props로 안 넘겨져서 훅 함수 내에서 유틸 함수를 반환값으로 주고 그걸 호출하는 방식을 사용했습니다.
<br />
=> [ApplicationPage] 리코일 초기화 위치 변경

src/views/ApplicationPage/components/ServiceHistory.tsx
- close #458
<br />
- 시술 내역 추가 버튼 삭제
<br />
☑**기존 코드**
- 시술 내역 3개까지 추가 가능
- 추가 버튼은 항상 보여주지만 3개 이상으로 리스트가 추가되지는 않음
☑**리팩토링 이후 코드**
- 시술 내역 3개까지 추가 가능
- 시술 내역이 3개가 되면 추가 버튼이 사라짐
```tsx
{serviceHistory.hairServiceRecords.length < MAX_LENGTH && (
<S.AddHistoryBtn type="button" onClick={addHistory}>
{INFO_MESSAGE.ADD_HISTORY}
</S.AddHistoryBtn>
)}
```
<br />
=> [QA] 최대 시술 내역 개수 도달시 내역 추가 버튼 삭제

src/views/@common/components/TextArea200.tsx
- close #459 
<br />
- 한글 글자 수 제한 함수 추가
<br />
기본 textare의 maxLength만을 이용하면 한글로 작성할 때 제한 글자 수를 넘는 경우가 발생했습니다.
1. 외부 영역 클릭 후, textarea의 추가 입력시 한 글자씩 추가 가능
2. 연속적으로 타이핑 시 한글은 201자까지 타이핑 가능
위의 2가지 경우를 모두 예외 처리해주기 위해 글자 수 제한 함수 로직을 추가했습니다.
❗ **주의** 
→ 한글일 경우에는 예외적으로 처리해줘야함 ! (초성, 중성, 종성 때문에)
→ 브라우저마다 한글 글자수를 다르게 인식하는 경우 때문에 substring 해서 글자수 고려해야 함 
```tsx
//MAX_LENGTH는 최대 글자 수로 별도로 설정
const textChangeFn = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
const text = e.target.value.length > MAX_LENGTH ? e.target.value.slice(0, MAX_LENGTH) : e.target.value;
setTextLength(text.length); // 현재 글자 수 
setName(text); // 화면에 노출되는 값
onChangeFn(text); // 변수에 저장
};
```
<br />
=> [QA] textarea 한글 글자 수 제한

tsconfig.node.json, vite.config.ts
- close #471 
<br />
- vite-bundle-visualizer를 통해 번들 구성 체크 
- html2canvas chunk를 분리시키기 위해 rollupOptions.output 추가 
- vite.config.ts에서 발생하는 타입 에러를 해결하고자 tsconfig.node.json에 옵션 추가 
<br />
💈**vite-bundle-visualizer를 통해 번들 구성 체크** 
번들 사이즈 체크해주기 위해서 vite-bundle-visualizer npx로 일회성 실행 했어요! 
이렇게 나왔는데 
가장 크게 차지하는 친구가 html2canvas 라이브러리였어요. 
근데 아시다시피 + 보시다시피 저희가 html2canvas를 지원하기 마지막 페이지에서 지원서 캡쳐할때만 사용하잖아요?? 
특정한 기능, 특정한 뷰, 특정한 액션에 의해서만 사용되는 친구인데 초기 번들 사이즈에 가장 많은 영역을 차지해주고 있는게 참 언짢지요 
그래서 chunk를 분리해서 초기 번들에서 빼줬습니다! 
💈 **html2canvas chunk를 분리시키기 위해 rollupOptions.output 추가** 
빌드를 돌리면 터미널에서 500kb가 넘는 청크가 있다 ~ build.rollupOptions.output.manualChunks 를 써서 청킹을 개선해라 ~ 이 경고가 보기 싫으면 build.ChunkSizeWarningLimit 을 바꿔서 청크 사이즈 제한을 조정해라 ~ 라는 워닝이 뜨는걸 볼 수 있어요.
여기서 말하는 build.rollupOptions.output.manualChunks 를 써서 …
=> [Refactor] html2canvas chunk 분리 및 tsconfig.node.json 옵션 추가
