TEAM-MODDY/moddy-web

.stylelintrc, package.json, yarn.lock
- close #6 
<br/>
<br />
🗣️  **`settings.json` 에 다음을 추가해주세요!** 
```JSON
"editor.codeActionsOnSave": {
"source.fixAll.stylelint": true
},
"stylelint.validate": ["typescriptreact"]
```
이걸 추가해야 저장 시에 lint설정에 맞게 바로 수정이 됩니다
<br/>
`문제` : 저장 시 알 수 없는 구문이 자꾸 styled-component 속성 위치에 추가됨
`해결` : customSyntax 관련 구문 overrides로 수정
`참고` : https://stylelint.io/migration-guide/to-15, https://seongyeoni.tistory.com/192
=> [Setting] Stylelint 세팅

.stylelintrc, src/styles/GlobalStyle.ts
=> [Setting] globalStyle과 styleling 충돌 해결

.stylelintrc
- close #12 
<br />
- 커스텀 오더에서 누락된 속성을 추가하였습니다
<br />
=> [Setting] stylelint 누락 속성 추가

.eslintrc.json, index.html, src/App.tsx, src/styles/Theme.ts, src/styles/fonts/font.css, src/styles/style.d.ts
- close #9 
<br />
- Theme 설정 
```typescript
const colors = {
ModdyBlue: '#236ffF'
//생략
}
const fonts = {
Title01: css`
font-family:
'Pretendard Variable',
font-style: normal;
font-weight: 700;
font-size: 2.2rem;
line-height: 2.8rem;
`, 
//생략
}
const theme: DefaultTheme = {
colors,
fonts,
};
``` 
- 사용하실 때는     `${({ theme: { fonts } }) => fonts.Title01};` 이렇게 사용하시면 됩니다! 
<br />
- 폰트 적용 오류
영문 Google font로 가져오는데 따로 css 파일 만들어서 가져오는 과정에서 적용이 안되는 문제가 있어서 index.html 에 link 태그로 연결해서 가져왔습니다!
```typescript
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=MuseoModerno:ital,wght@1,200;1,300;1,400&display=swap" rel="stylesheet">
``` 
- eslint 오류
'React' must be in …
=> [Setting]Theme 설정

src/styles/Theme.ts, src/styles/style.d.ts
=> [Setting]네이밍 수정

src/App.tsx, src/pages/ModelInfoPage.tsx, src/styles/GlobalStyle.ts, src/views/@common/components/Button.tsx, src/views/@common/components/Header.tsx, src/views/@common/components/ModelOffer.tsx, src/views/ModelInfoPage/components/CopyButton.tsx, src/views/ModelInfoPage/components/OfferDetail.tsx, src/views/ModelInfoPage/components/OfferDetailBox.tsx, src/views/ModelInfoPage/hooks/types.ts
- close #issue_number
<br />
- 무슨 이유로 어떻게 코드를 변경했는지
- 이부분에 주목해서 리뷰해주세요!
<br />
- 겪었던 트러블 슈팅이 있다면 작성
- 없다면 삭제!
<br />
=> Merge Feature/model info page to develop

src/pages/MainPage.tsx, src/views/@common/components/ProgressBar.tsx
- close #42 
<br />
```jsx
<ProgressBar whole={5} current={3} />
```
- whole : 전체 단계 수 
- current : 현재 단계 수 
위 처럼 사용했을 경우 아래의 스크린샷 처럼 나옴 
<br />
=> [Common] 공통 컴포넌트 - ProgressBar

src/views/@common/components/Button.tsx
- close #47 
<br />
```ts
interface ButtonProps {
text: string;
isFixed?: boolean;
onClickFn: () => void;
disabled?: boolean;
icon?: ReactNode;
}
```
- text (필수) : 버튼 텍스트
- isFixed (선택) : 버튼을 fixed할 여부 
- onClickFn (필수) : onClick function `()=>void` 형태로
- disabled (선택) : 버튼 비활성화 여부 
- icon (선택) : 아이콘 필요할 때 svg 컴포넌트 넣어주기 
```jsx
<Button text="뫄뫄" onClickFn={() => console.log('뫄')} />
<Button text="뫄뫄" onClickFn={() => console.log('뫄')} isFixed />
<Button text="뫄뫄" onClickFn={() => console.log('뫄')} disabled />
<Button text="뫄뫄" onClickFn={() => console.log('뫄')} icon={<IcDownload />} />
```
<br />
=> [Common] CTA 추상화 

src/styles/Theme.ts, src/styles/style.d.ts, src/views/@common/components/Modal.tsx
- close #49 
<br />
모든 props가 필수입니다. 
```ts
interface ModalProps {
title: string;
description: string;
leftBtnText: string;
rightBtnText: string;
leftBtnFn: () => void;
rightBtnFn: () => void;
}
```
- title : 모달 제목으로 들어갈 텍스트
- description: 회색 글씨로 들어갈 텍스트
- 🚨개행이 필요한 곳에 `<br/>`을 입력해주세요 
- leftBtnText, rightBtnText: 각 버튼에 들어갈 텍스트 
- leftBtnFn, rightBtnFn: 각 버튼의 onClick function 
```tsx
<Modal
title="작성을 취소하시겠습니까?"
description="지금 작성을 취소하면<br/>작성 중인 내용이 사라져요."
leftBtnText="취소하기"
rightBtnText="계속하기"
leftBtnFn={() => console.log('왼쪽버튼클릭')}
rightBtnFn={() => console.log('오른쪽버튼클릭')}
/>
```
<br />
<br />
=> [Common] 공통 컴포넌트 - 모달 구현 

src/styles/Theme.ts, src/styles/style.d.ts, src/views/@common/components/Modal.tsx, src/views/@common/components/ToastMessage.tsx
- close #51 
<br />
```ts
interface ToastMessageProps {
text: string;
setter: React.Dispatch<React.SetStateAction<boolean>>;
}
```
- text : 토스트 메시지의 텍스트
- setter: 토스트 메시지를 껐다켰다 할 수 있는 state setter 
```tsx
const [isToastOpen, setToastOpen] = useState<boolean>(false);
return (
<div>
<Test type="button" onClick={() => setToastOpen(true)}>
토스트 테스트용 버튼
</Test>
{isToastOpen && <ToastMessage text="회원탈퇴가 완료되었습니다." setter={setToastOpen} />}
</div>
);
```
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/1dcb380b-4d32-4543-bd5a-8465b44a5c05
=> [Common] 공통 컴포넌트 - 토스트 메시지 구현 

.eslintrc.json, src/App.tsx, src/pages/AgreementPage.tsx, src/views/@common/components/Button.tsx, src/views/@common/components/Header.tsx, src/views/AgreementPage/components/AgreementItem.tsx, src/views/AgreementPage/components/AgreementList.tsx
- close #53 
<br />
- AgreementPage 내부에 헤더와 CTA를 제외한 몸체는 AgreementList 컴포넌트로 구현하였습니다. 
- AgreementList 컴포넌트 내부엔 각 줄을 AgreementItem으로 컴포넌트화하였습니다. 
```tsx
interface AgreementItemProps {
firstItem?: boolean;
text: string;
isChecked: boolean;
onClickCheck: () => void;
link?: string;
}
```
- firstItem : `모든 약관에 동의합니다` 항목인지 아닌지 체크 
- 첫번째 아이템일 경우 색상, 폰트, 체크박스 클릭 시 발생하는 이벤트가 다르기 때문에 props로 구분해주었습니다. 
- text : 체크박스 내용 
- isChecked : 체크박스 체크 여부 
- onClickCheck : 체크박스 클릭 시 발생하는 함수 
- 배열state의 특정 요소의 값을 변경해야 해서 setter로만 실행할 수 없고, 배열을 얕은복사->특정 요소 값 바꾸기->setter로 업데이트 하는 함수를 만들었습니다. 
- link : 더보기 버튼 클릭 시 관련 약관 작성되어있는 노션 외부링크로 이동
**▶️ AgreementPage**
```tsx
const AgreementPage = () => {
const navigate = useNavigate();
return (
<div>
<Header title="이용약관" isBackBtnExist backFn={() => navigate(-1)} /> …
```
=> [Agreement] 이용약관 페이지 구현 

src/App.tsx, src/pages/MyQuitPage.tsx, src/views/MyQuit/components/MyQuitCheck.tsx, src/views/MyQuit/components/MyQuitText.tsx
- close #62 
<br />
특별한 사항 없습니다. 
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/1df808ef-77a4-46c3-b435-d7bda4b047f8
=> [MyPage] 회원탈퇴 페이지 퍼블리싱 

.eslintrc.json, package.json, src/pages/MyPage.tsx, src/pages/MyQuitPage.tsx, src/views/@common/components/Modal.tsx, src/views/MyPage/components/MyInfo.tsx, src/views/MyPage/components/MyMenuItem.tsx, src/views/MyPage/components/MyMenuList.tsx, tsconfig.json, vite.config.ts, yarn.lock
- close #63  
<br />
구현해놓은 modal 공통 컴포넌트를 활용해서 간단하게 구현하였습니다 
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/7dbc4b37-7324-456c-9563-5cf91e891ddc
=> [MyPage] 로그아웃, 회원탈퇴 기능 구현 

src/views/@common/components/Header.tsx, src/views/@common/components/Modal.tsx, src/views/@common/components/ProgressBar.tsx, src/views/@common/components/ToastMessage.tsx, src/views/MyPage/components/MyFooter.tsx
close #92 
<br />
`position: fixed`를 줄 경우, 다음과 같은 항목들을 꼭 체크해야 합니다. 
- `max-width: 43rem`을 주어서 데탑뷰로 볼 시 양쪽으로 퍼지지 않는지 
- `left:0`이나 `right: 0`을 주지 않았는지 -> 줄 경우, 데탑뷰일 때 43rem 상태에서 사이드로 붙어버립니다
=> [Common] fixed 컴포넌트 스타일 수정 

src/views/@common/components/Modal.tsx, src/views/@common/components/ToastMessage.tsx
close #117 
<br />
왼쪽으로 붙는 이슈해결
<br />
=> [Common] 데스크탑뷰 fixed 컴포넌트 위치 변경

src/views/@common/hooks/api.ts
close #111 
<br />
- axiosInstance 쓰고 싶으면 api 쓰세용~
- accessToken 받아서 저장할 땐 `setToken(토큰키)`
- accessToken 사용할 땐 `getToken()`
- 토큰 지울 땐 `removeToken()`
<br />
=> [Common] axiosInstance 생성

src/views/@common/components/Input.tsx
close #132 
<br />
```tsx
interface InputProps {
placeholderText: string;
initialValue: string;
onChangeFn: (value: string) => void;
}
const Input = ({ placeholderText, initialValue, onChangeFn }: InputProps) => {
const [name, setName] = useState(initialValue);
return (
<S.InputLayout>
<S.Input
placeholder={placeholderText}
value={name}
onChange={(e) => {
setName(e.target.value);
onChangeFn(e.target.value);
}}
/>
{name !== '' && <IcCheckBlue />}
</S.InputLayout>
);
};
```
=> [Common] Input에 initialValue prop 추가 

src/views/MyPage/hooks/type.ts, src/views/MyPage/hooks/useGetUser.ts
close #127 
<br />
react query를 빨리 도입하고 싶다. useEffect, useState 정리해주고 싶다. 
<br />
=> [MyPage] useGetUser 통신 구현 

src/views/MyPage/hooks/type.ts, src/views/MyPage/hooks/usePostUser.ts
=> [MyPage] usePostUser API 통힌 구현 

src/views/MyPage/hooks/type.ts, src/views/MyPage/hooks/useDeleteUser.ts, src/views/MyPage/hooks/usePostUser.ts
=> [MyPage] 회원탈퇴 API 구현 

src/pages/LoginPage.tsx, src/pages/MyPage.tsx, src/pages/MyQuitPage.tsx, src/views/@common/constants/modalText.ts, src/views/LoginPage/components/LoginText.tsx
=> [LoginPage, MyPage, QuitPage] UX라이팅 변경 사항 

src/App.tsx, src/views/LoginPage/components/LoginButton.tsx, src/views/LoginPage/components/LoginCallback.tsx, src/views/LoginPage/constants/kakaoLink.ts, src/views/LoginPage/hooks/type.ts, src/views/LoginPage/hooks/usePostLogin.ts
=> [LoginPage] 우리아이 돌려내

src/views/SignUpPage/components/Profile.tsx, src/views/SignUpPage/components/ProfileUpload.tsx, src/views/SignUpPage/utils/readImg.ts
close #169 
<br />
이미지 추가 기능 구현 + 추가 되었을 때 CTA 활성화
<br />
```typescript
const [isImageUploaded, setImageUploaded] = useState(false);
const handleImageUpload = () => {
setImageUploaded(true);
};
const isActive = InstaIDValue && NaverLinkValue !== '' && isImageUploaded;
``` 
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/111034927/cf17258f-8ad5-4fb3-86a2-292aae8a8ea6
=> [SignUpPage] 이미지 추가 기능 구현

src/views/AgreementPage/components/AgreementList.tsx, src/views/AgreementPage/constants/AGREEMENT_LINK.ts
=> [AgreementPage] 상수 빼주기 

src/pages/ModelInfoPage.tsx, src/pages/OfferDetailSection.tsx, src/views/ModelInfoPage/components/DetailBox.tsx, src/views/ModelInfoPage/components/ModelOfferPage.tsx, src/views/ModelInfoPage/constants/CONDITION_DATA.tsx, src/views/ModelInfoPage/constants/CONDITION_LIST.ts, src/views/ModelInfoPage/hooks/types.ts, src/views/ModelInfoPage/hooks/useGetApplication.ts, src/views/ModelInfoPage/hooks/usePostApplication.ts
close #196 
<br />
아래 세 파일만 봐주시면 됩니다! 
- views > ModelInfoPage > hooks > usePostApplication.ts
- views > ModelInfoPage > components > ModelOfferPage.tsx
- view > ModelInfoPage > constants > CONDITION_LIST.ts
```ts
const usePostApplication = (applicationId: number, offerDetail: string, preferOfferConditions: boolean[]) => {
const navigate = useNavigate();
const conditionList = preferOfferConditions
.map((bool, idx) => (bool ? CONDITION_LIST[idx] : ''))
.filter((val) => val !== '');
const postApplication = async () => {
try {
await api.post(
`/designer/${applicationId}/offer`,
{
offerDetail: offerDetail,
preferOfferConditions: conditionList,
},
{
headers: {
Authorization:
'Bearer ~ ',
},
},
);
navigate('/model-info/model-offer/sent-complete');
} catch (err) {
navigate('/error'); …
```
=> [ModelInfoPage] usePostApplication API 구현 

.stylelintrc, src/App.tsx, src/views/@common/components/Loading.tsx
close #214 
<br />
필요하신 부분에 **common**에 있는 `<Loading />` 불러서 사용하세요 ~ 
https://github.com/TEAM-MODDY/moddy-web/assets/81505421/388546a6-c466-4add-8efb-47464a834aba
=> [Common] Loading 컴포넌트 제작

src/recoil/atoms/signUpState.ts, src/views/@common/constants/userType.ts, src/views/MainPage/hooks/useGetMain.tsx, src/views/SignUpPage/components/OpenChatLink.tsx, src/views/SignUpPage/components/PreferRegion.tsx, src/views/SignUpPage/components/ProfileUpload.tsx, src/views/SignUpPage/components/ShopInfo.tsx, src/views/SignUpPage/constants/days.ts, src/views/SignUpPage/hooks/type.ts, src/views/SignUpPage/hooks/useModelSignUp.ts, src/views/SignUpPage/hooks/usePostDesignerSignUp.ts, src/views/SignUpPage/hooks/usePostModelSignUp.ts
close #211
<br />
민서가 만들어둔 휴무일 배열 ( [true,false,false ...] )형식이 서버 ( ['MON'] )와 맞지 않아서 해당 내용 수정하였습니다
```javascript
export const DAYS = {
월: 'MON',
화: 'TUE',
수: 'WED',
목: 'THU',
금: 'FRI',
토: 'SAT',
일: 'SUN',
};
if (tempClicked[index] === '') {
tempClicked[index] = DAYS[dayValue as keyof typeof DAYS];
} else {
tempClicked[index] = '';
}
...
```
<br />
처음에는 노션을 보고 착각해서 profileImg를 formData 객체로 선언하고 넣어준 다음 회원가입에 필요한 데이터와 함께 requestBody에 넣어주고 Content-type은  multipart/form-data로 설정해줬다. 그래서 서버에서는 MultiPart형식의 이미지 url을 받아야하는데  계속 [Object FormData]형식으로 갔던 것이다
알고 보니 그렇게 하는 것이 아니었고  reaquestBody를 FormData 형식으로 넘겨줘야 하는 것인데 이렇게 하니까 designerInfo 데이터를 서버에서 읽을 수가 없었다 이걸 어떻게 처리해야할까,,,,
결론부터 말하자면 파일은 파일형식으로 가져오고 reaquestBody를 FormData 객체로 만들어주고 이 객체에 profileImg 파일과 designerInfo json데이터를 넣어줬다.
(타투어의 코드를 …
=> [SignUpPage] 디자이너 회원가입 API 연결

src/pages/ModelInfoPage.tsx, src/views/@common/components/ToastMessage.tsx, src/views/ModelInfoPage/components/OfferSentCompletePage.tsx, src/views/ModelInfoPage/hooks/useGetApplication.ts
close #209
<br />
```typescript
const isSend = data?.applicationInfo.isSend;
<Button
text={isSend ? '제안완료' : '제안하기'}
isFixed={false}
onClickFn={handleOnClickOffer}
disabled={isSend ? true : false}
/>
``` 
<br />
<br />
=> [ModelInfoPage] isSend 따라 버튼 비활성화 처리

src/App.tsx, src/pages/OfferInfoPage.tsx, src/views/ModelInfoPage/hooks/useGetApplication.ts, src/views/ModelInfoPage/hooks/usePostApplication.ts, src/views/OfferInfoPage/components/DesignerInfoSection.tsx, src/views/OfferInfoPage/components/DirectionModal.tsx, src/views/OfferInfoPage/components/OfferDetailSection.tsx, src/views/OfferInfoPage/hooks/useGetAgree.ts, src/views/OfferInfoPage/hooks/useGetOfferModel.ts, src/views/OfferInfoPage/hooks/usePutOfferModel.ts, src/views/SignUpPage/hooks/usePostModelSignUp.ts
close #238 
<br />
```typescript
const DirectionModal = ({ isModal, onClose, offerId }: DirectionModalProps) => {
const navigate = useNavigate();
const { postOffer } = usePutOfferModel(offerId);
``` 
<br />
=> [OfferInfoPage] navigate로 넘겨주는 OfferId값 받기

src/views/MainPage/components/Banner.tsx
close #241 
<br />
배너 높이가 이상해서 수정해줬습니다
=> [MainPage] 배너 높이 수정

package-lock.json, package.json, src/main.tsx, src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/MyPage/components/MyInfo.tsx, src/views/MyPage/hooks/useDeleteUser.ts, src/views/MyPage/hooks/usePostLogout.ts, src/views/MyQuit/components/MyQuitCheck.tsx, src/views/SignUpPage/components/OpenChatLink.tsx, src/views/SignUpPage/components/UserType.tsx, src/views/SignUpPage/hooks/useGetRegion.ts, src/views/SignUpPage/hooks/usePostModelSignUp.ts, yarn.lock
=> [Merge]yarn build로 오류잡기

src/views/@common/utils/removeToken.ts, src/views/LoginPage/hooks/usePostLogin.ts
=> [bugfix] userType 타입 변경 

vercel.json
- close #269 
<br />
배포 후 소셜 로그인할 때 redirect 시 에러
=> [hotfix] vercel.json 세팅 

src/pages/ConfirmPage.tsx, src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/ApplicationPage/hooks/type.ts, src/views/ApplicationPage/hooks/useGetUser.ts
- close #268
<br />
- 최종 지원서의 창이 뜰 때, get을 통해 user의 정보를 불러오는 API입니다
```tsx
onst useGetUser = () => {
const [data, setData] = useState<ApplyUserProps>();
const navigate = useNavigate();
const getUser = async () => {
try {
const response = await api.get('/model/application/user');
setData(response.data.data);
} catch (err) {
console.log(err);
navigate('/error');
}
};
useEffect(() => {
getUser();
}, []);
return data;
};
```
<br />
=> [ApplicationPage] GET API 연결

src/views/@common/components/Header.tsx, src/views/MyPage/components/MyFooter.tsx, src/views/MyPage/components/MyMenuList.tsx, src/views/MyPage/constants/link.ts
- close #223
<br />
마이페이지에서 연결되어야 하는 외부 링크 상수화 해서 넣어줬습니다
=> [Release] 전체적으로 navigate 연결

src/pages/ConfirmPage.tsx, src/views/MyPage/components/MyInfo.tsx
- close #282 
<br />
src를 바로 작성해준 친구들이 엑박이 뜨더라구요 
그래서 import 문 별도로 빼준 뒤 src에 변수를 넣어주는 식으로 해결했습니다 
```tsx
import ImgLetter from '@images/img_letter.png';
...
```
=> [QA] 이미지 import 에러 해결 

index.html
=> [QA] og image 안뜨는 문제 해결 

src/pages/OfferInfoPage.tsx
- close #288
<br />
state.id 로 되어있어서 undefined로 넘어가던거 변경해서 넣었습니당
```typescript
const { state } = useLocation();
const offerId = state;
``` 
<br />
<br />
=> [QA]Offer Id 값 get 가져오기 수정

index.html
=> [OP] Google Analytics 태그 설치

src/App.tsx, src/pages/ModelOfferPage.tsx, src/views/@common/components/Header.tsx
- close #295 
<br />
```tsx
{isOpenModal && (
<Modal
title="작성을 취소하시겠습니까?"
description="지금 작성을 취소하면<br/>작성 중인 내용이 사라져요."
leftBtnText="계속하기"
rightBtnText="취소하기"
leftBtnFn={() => setOpenModal(false)}
rightBtnFn={() => (closeFn ? closeFn() : navigate('/'))}
/>
)}
```
<br />
<br />
=> [QA] 제안하기 이탈모달 오류 수정 

src/views/MyPage/components/MyMenuItem.tsx
=> [QA] cursor:pointer 일괄 적용 

src/views/MyPage/components/MyInfo.tsx
- close #289 
<br />
```tsx
& > img {
width: 8rem;
height: 8rem;
border: 1.5px solid ${({ theme }) => theme.colors.moddy_blue};
border-radius: 8px;
object-fit: cover;
background-color: ${({ theme }) => theme.colors.moddy_wt};
}
```
<br />
=> [QA] MyPage 프로필사진 디자인 변경 

src/App.tsx, src/pages/ModelOfferPage.tsx, src/views/@common/components/Header.tsx
- close #295 
https://github.com/TEAM-MODDY/moddy-web/pull/298
=> [QA] 작성하기 이탈모달 오류 해결 

src/views/ModelInfoPage/constants/CONDITION_LIST.ts
- close #310
<br />
```typescript
export const CONDITION_LIST = ['CAMERA', 'SNS', 'FREE', 'MASK', 'PHOTOSHOP', 'SMALL_PAY'];
``` 
<br />
=> [ModelInfoPage] 소정의 약값 constant 수정

src/pages/AgreementPage.tsx, src/views/SignUpPage/components/EnterProfile.tsx
- close #330
1. 회원가입 도중 닫기 눌렀을 때 에러 뜸
2. Agreement 페이지에서 뒤로 가기 했을 때 에러 뜸
https://github.com/TEAM-MODDY/moddy-web/assets/46593078/cad2d7c2-39b0-4222-95e3-f2b76a1188da
<br />
이탈 시 토큰 날려주고 Navigate 처리 해줬습니다
```javascript
const handleChurn = () => {
removeToken();
navigate('/');
};
```
<br />
https://github.com/TEAM-MODDY/moddy-web/assets/46593078/bd905fe2-21a8-433d-87be-89f1067e1e67
=> [QA] 회원가입 중 이탈 시 토큰 삭제

src/pages/LoginPage.tsx, src/pages/ModelInfoPage.tsx, src/pages/ModelOfferPage.tsx, src/pages/OfferInfoPage.tsx, src/views/@common/components/Button.tsx, src/views/@common/components/Modal.tsx, src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/LoginPage/components/LoginButton.tsx, src/views/MainPage/components/Card.tsx, src/views/MainPage/components/TopSheet.tsx, src/views/OfferInfoPage/components/ButtonBox.tsx, src/views/SignUpPage/components/DesignerInfo.tsx, src/views/SignUpPage/components/OpenChatLink.tsx, src/views/SignUpPage/components/PersonalInfo.tsx, src/views/SignUpPage/components/PhoneNumber.tsx, src/views/SignUpPage/components/PreferRegion.tsx, src/views/SignUpPage/components/Profile.tsx, src/views/SignUpPage/components/ShopInfo.tsx, src/views/SignUpPage/components/UserType.tsx
- close #339
각 트리거에 해당 하는 id 넣어 줬습니다 배포 후 테스트 해봐야 작동 확인 될 듯합니다
=> [OP] Google Analytics 버튼 클릭 추적

index.html, src/pages/LoginPage.tsx, src/pages/ModelInfoPage.tsx, src/pages/ModelOfferPage.tsx, src/pages/OfferInfoPage.tsx, src/views/@common/components/Button.tsx, src/views/@common/components/Modal.tsx, src/views/ApplicationPage/components/ApplicationResult.tsx, src/views/LoginPage/components/LoginButton.tsx, src/views/MainPage/components/Card.tsx, src/views/MainPage/components/TopSheet.tsx, src/views/OfferInfoPage/components/ButtonBox.tsx, src/views/SignUpPage/components/DesignerInfo.tsx, src/views/SignUpPage/components/OpenChatLink.tsx, src/views/SignUpPage/components/PersonalInfo.tsx, src/views/SignUpPage/components/PhoneNumber.tsx, src/views/SignUpPage/components/PreferRegion.tsx, src/views/SignUpPage/components/Profile.tsx, src/views/SignUpPage/components/ShopInfo.tsx, src/views/SignUpPage/components/UserType.tsx
=> [OP] Google 태그 관리자 설치

src/pages/OfferInfoPage.tsx
- close #348
오른쪽으로 선이 길게 길어지는 문제
<br />
vw -> % 로
<br />
=> [QA] 중간선 단위 변경

src/views/ApplicationPage/components/ProfileUpload.tsx, src/views/ApplicationPage/components/ServiceHistory.tsx
- close #350 
빈 배열에 빈 문자열을 가진 객체가 들어가는 경우 서버에서 처리 못하는 문제 발생
<br />
선택된 값이 없는 경우 예외 처리해서 빈 문자열로 만들기
```tsx
const exceptionNull = () => {
if (
serviceHistory.hairServiceRecords[0].hairService === '' ||
serviceHistory.hairServiceRecords[0].hairServiceTerm === ''
)
setServiceHistory({ ...serviceHistory, hairServiceRecords: [] });
};
```
<br />
=> [QA] POST 빈 문자열 처리

src/views/@common/components/Header.tsx
- close #360 
<br />
- 나가기 버튼, 뒤로가기 버튼 없을 때 클릭 안되게 수정
<br />
```jsx
<button onClick={backFn ? backFn : () => navigate(-1)}>
{isBackBtnExist ? <IcLeftBlack /> : <S.HeaderBlankBox />}
</button>
```
조건식이 button안에 있어서 해당 버그가 발생했습니다 밖으로 꺼내서 해결해줬습니다
```jsx
{isBackBtnExist ? (
<button onClick={backFn ? backFn : () => navigate(-1)}>
<IcLeftBlack />
</button>
) : (
<S.HeaderBlankBox />
)}
```
=> [Common] 헤더 아이콘 클릭 버그 수정

src/views/@common/utils/regex.ts, src/views/SignUpPage/components/PersonalInfo.tsx
- close #372
<br />
- LimitInput 교체
- 커스텀 Input 교체
<br />
PesonalInfo.tsx 에서 사용하던 LimitInput과 임의로 만든 커스텀 Input 컴포넌트를 공통 Input 컴포넌트로 교체하는 작업을 하였습니다
<br />
=> [SignUpPage] 커스텀 Input 컴포넌트를 공통 Input 컴포넌트로 교체

src/views/SignUpPage/components/ShopInfo.tsx
- close #369 
<br />
- 여기도 리팩토링 진행! 
<br />
막 불필요한 모달 코드도 있고... 싹다 정리했습니다... 정리방식은 이전 PR참고해주시면 될 것 같습니다:) 속이 다 시원하네요...
`이전 코드`
```typescript
const ShopInfo = ({ setStep }: EnterProfileProp) => {
//recoil 적용 CTA 클릭시 저장
const [shopInfo, setShopInfo] = useRecoilState(shopInfoState);
const [addressInfo, setAddressInfo] = useRecoilState(addressState);
const [detailAddressInfo, setDetailAddressInfo] = useRecoilState(detailShopInfoState);
const [clickedDateInfo, setClickedDateInfo] = useRecoilState(dateState);
const [placeTextValue, setPlaceTextValue] = useState(shopInfo.data);
const [isClicked, setIsClicked] = useState<string[]>(clickedDateInfo.data);
const [isOpenModal, setOpenModal] = useState(false);
const [Address, setAddress] = useState<string>('');
const [isAddressModal, …
```
=> [SignUpPage]주소 입력 페이지 set함수 관리

src/recoil/atoms/applicationState.ts, src/views/ApplicationPage/components/ServiceHistory.tsx, src/views/ApplicationPage/components/ServiceHistoryListItem.tsx, src/views/ApplicationPage/constants/message.ts
[ApplicationPage] 시술 내역 드롭다운 박스 단일 활성화 기능 추가 (#385)
* refactor: 불필요한 코드 삭제
* feat: ref 훅 추가
* refactor: 시술 선택, 기간 선택 state 통합
* fix: state 조건 추가
* feat: 단일 드롭다운 활성화
* feat: 외부 영역 클릭시 드롭다운 선택 해제
* chore: 불필요한 코드 제거
* refactor: 중복되는 코드 정리
[ApplicationmPage] 시술 내역 경고 모달창 추가 (#422)
* feat: 경고 모달창 구현
* refactor: 드롭다운 박스 선택 범위 수정
=> [Merge] feature/SP2 => develop

src/recoil/atoms/applicationState.ts, src/views/ApplicationPage/components/DropDown.tsx, src/views/ApplicationPage/components/ServiceHistory.tsx, src/views/ApplicationPage/components/ServiceHistoryListItem.tsx
- close #420 
<br />
- 드롭다운 컴포넌트 분리
<br />
이전 코드 참조하기: https://github.com/TEAM-MODDY/moddy-web/pull/385
저번 PR에서 단일 활성화 기능을 추가하며 상태 관리를 와방 뜯어고쳤었는데요. 사실 코드가 마음에 안 들었습니다,,
위 그림에서 빨간 박스로 처져있는 부분이 저번 코드의 가장 작은 컴포넌트였습니다. `시술 내역 리스트 하나 = 컴포넌트 하나` 이렇게 구현한 건데요. 거슬렸던 부분은
1. 리스트 컴포넌트 내에서 두 드롭다운을 분리하는 추가적인 조건을 걸어줘야한다는 점
2. 드롭다운 자체의 재사용성이 떨어진다는 점 (나중에 선택 항목이 추가되거나 하면 골칫덩어리 이슈 예상,,)
3. 드롭다운 활성화를 리스트 단위로 관리하고 있어서 리스트의 인덱스 값으로 두 드롭다운의 활성화를 관리하고 있다는 점
...
하여튼, 여러모로 계속 신경이 쓰였습니다 !
그래서 드롭다운 하나당 한 컴포넌트로 분리해서 재사용성을 높이고 더 의미있고 간단한 코드를 작성하기 위해 리팩토링을 진행해주었습니다.
✅ 기존에 리스트의 idx 값을 담아주던 `state` 제거
이제 각 드롭다운 컴포넌트에서 활성화 여부를 관리해주면서 선택 중인 리스트의 `index` 값을 저장할 필요가 없어졌습니다.
```tsx
/*기존 코드*/
//아래 상태와 관련된 코드들은 전부 제거
const [currentDropDown, setCurrentDropDown] = useState<number | null>(null);
//...
<ServiceHistoryListItem …
```
=> [ApplicationPage] 시술 내역 드롭다운 컴포넌트 분리

src/styles/Theme.ts, src/styles/style.d.ts, src/views/@common/assets/icons/ic_right_grey30.svg, src/views/@common/assets/icons/index.ts, src/views/SignUpPage/components/7_오픈채팅링크/OpenChatLink.tsx, src/views/SignUpPage/constants/message.ts
- close #443
<br />
-  포트폴리오 링크 입력 라이팅 수정
-  1:1 오픈채팅 링크 입력 라이팅 수정
-  1:1 오픈채팅 더알아보기 이동 링크 추가
<br />
=> [SignUpPage] 디자이너 회원가입 라이팅 수정

src/views/EditInfoPage/components/ModelEditInfoSection.tsx, src/views/EditInfoPage/components/ModelInfo.tsx, src/views/EditInfoPage/components/RegionList.tsx, src/views/EditInfoPage/constants/message.ts, src/views/EditInfoPage/hooks/type.ts, src/views/EditInfoPage/hooks/useGetModelUser.ts, src/views/EditInfoPage/hooks/useGetRegionList.ts, src/views/SignUpPage/components/3_선호지역선택/PreferRegion.tsx, src/views/SignUpPage/components/3_선호지역선택/RegionItem.tsx
- close #450 
<br />
- 지역 리스트 GET api
- 유저 정보 GET api
<br />
GET api 2개 받아오고 레이아웃 살짝 깨지는 부분이 있어서 수정했어요
<br />
>전화번호 이슈.. .. .로 모자이크 할게요
=> [EditPage] GET API

src/pages/LoginPage.tsx
- close #467 
<br />
- 요청받은 autoplay 옵션 추가 (3.75초) 
<br />
https://github.com/user-attachments/assets/f406faeb-daab-40a0-9dd3-4b5716207dbf
=> [ Design ] slide autoPlay option 추가

src/pages/LoginPage.tsx
<br />
- slider auto play 옵션 추가
=> [Deploy] auto play 옵션 추가 

src/views/ApplicationPage/components/Profile.tsx
- close #477 
<br />
- 프로필 이미지 필수로 첨부하도록 버튼 disabled 조건 수정 
- 인스타 아이디는 선택항목이기 떄문에 disabled 조건에서 제외
- 불필요해진 state 삭제 
<br />
https://github.com/user-attachments/assets/9075a2d4-eaad-4dbf-a46e-216288cd544b
=> [Fix] 프로필이미지 필수, 인스타아이디 선택 조건 수정

src/global.d.ts, src/pages/ApplicationPage.tsx, src/pages/SignUpPage.tsx, src/views/@common/hooks/useTrackPageView.ts, src/views/MainPage/components/Card.tsx, src/views/OfferInfoPage/components/DirectionModal.tsx, yarn.lock
- close #476 
<br />
- [1.5순위 추가 ](https://github.com/TEAM-MODDY/moddy-web/pull/479/commits/2de45af496ba3e25b56a52ae21599744842685dc)
- 헤어 디자이너 제안 클릭 
- 헤어 디자이너 제안 수락 클릭 
- 2순위
- 카카오 로그인 페이지 ~ 기본 정보 입력 완료까지 각 스텝별 페이지 뷰 
- 모델 지원 과정에서의 각 스텝별 페이지 뷰 
<br />
<br />
=> [OP] GA P2, P3 트리거 추가 

src/global.d.ts, src/pages/ApplicationPage.tsx, src/pages/SignUpPage.tsx, src/views/@common/hooks/useTrackPageView.ts, src/views/MainPage/components/Card.tsx, src/views/OfferInfoPage/components/DirectionModal.tsx, yarn.lock
* chore: lock file modified
* feat: GA 트리거 P2 두가지 추가
* fix: global.d.ts 확장
* feat: 가입,지원하기 페이지별 pageview 트리거 추가
* fix: page view 이벤트 트래커 수정
=> [Deploy] GA P2, P3 반영 

src/pages/SignUpPage.tsx, src/views/SignUpPage/assets/icons/ic_right_blue.svg, src/views/SignUpPage/assets/icons/index.ts, src/views/SignUpPage/components/0_유저유형선택/UserType.tsx, src/views/SignUpPage/components/1_기본정보입력/PersonalInfo.tsx, src/views/SignUpPage/components/2_전화번호인증/PhoneNumber.tsx, src/views/SignUpPage/components/4_샵정보/ShopInfo.tsx, src/views/SignUpPage/components/5_디자이너프로필/Profile.tsx, src/views/SignUpPage/components/6_디자이너소개/DesignerInfo.tsx, src/views/SignUpPage/components/index.ts, src/views/SignUpPage/components/디자이너코드/Code.tsx, src/views/SignUpPage/constants/message.ts, src/views/SignUpPage/constants/step.ts, src/views/SignUpPage/utils/enterProfileProp.ts
- close #481 
<br />
- 디자이너 인증코드 뷰 구현 
- 기능 구현 
<br />
https://github.com/user-attachments/assets/a460f037-99ac-471c-ba40-77a9a1b53d2b
=> [ Feat ] 디자이너 인증코드 단계 추가 구현 
